
export const assets =[

    {url:"./fondo.png",name:"Background"},

    {url:"./nene/Idle (1).png",name:"NeneIdle1"},
    {url:"./nene/Idle (2).png",name:"NeneIdle2"},
    {url:"./nene/Idle (3).png",name:"NeneIdle3"},
    {url:"./nene/Idle (4).png",name:"NeneIdle4"},
    {url:"./nene/Idle (5).png",name:"NeneIdle5"},
    {url:"./nene/Idle (6).png",name:"NeneIdle6"},
    {url:"./nene/Idle (7).png",name:"NeneIdle7"},
    {url:"./nene/Idle (8).png",name:"NeneIdle8"},
    {url:"./nene/Idle (9).png",name:"NeneIdle9"},
    {url:"./nene/Idle (10).png",name:"NeneIdle10"},
    {url:"./nene/Idle (11).png",name:"NeneIdle11"},
    {url:"./nene/Idle (12).png",name:"NeneIdle12"},
    {url:"./nene/Idle (13).png",name:"NeneIdle13"},
    {url:"./nene/Idle (14).png",name:"NeneIdle14"},
    {url:"./nene/Idle (15).png",name:"NeneIdle15"},

    {url:"./nene/Walk (1).png",name:"NeneWalk1"},
    {url:"./nene/Walk (2).png",name:"NeneWalk2"},
    {url:"./nene/Walk (3).png",name:"NeneWalk3"},
    {url:"./nene/Walk (4).png",name:"NeneWalk4"},
    {url:"./nene/Walk (5).png",name:"NeneWalk5"},
    {url:"./nene/Walk (6).png",name:"NeneWalk6"},
    {url:"./nene/Walk (7).png",name:"NeneWalk7"},
    {url:"./nene/Walk (8).png",name:"NeneWalk8"},
    {url:"./nene/Walk (9).png",name:"NeneWalk9"},
    {url:"./nene/Walk (10).png",name:"NeneWalk10"},
    {url:"./nene/Walk (11).png",name:"NeneWalk11"},
    {url:"./nene/Walk (12).png",name:"NeneWalk12"},
    {url:"./nene/Walk (13).png",name:"NeneWalk13"},
    {url:"./nene/Walk (14).png",name:"NeneWalk14"},
    {url:"./nene/Walk (15).png",name:"NeneWalk15"},

    {url:"./nene/Jump (1).png",name:"NeneJump1"},
    {url:"./nene/Jump (2).png",name:"NeneJump2"},
    {url:"./nene/Jump (3).png",name:"NeneJump3"},
    {url:"./nene/Jump (4).png",name:"NeneJump4"},
    {url:"./nene/Jump (5).png",name:"NeneJump5"},
    {url:"./nene/Jump (6).png",name:"NeneJump6"},
    {url:"./nene/Jump (7).png",name:"NeneJump7"},
    {url:"./nene/Jump (8).png",name:"NeneJump8"},
    {url:"./nene/Jump (9).png",name:"NeneJump9"},
    {url:"./nene/Jump (10).png",name:"NeneJump10"},
    {url:"./nene/Jump (11).png",name:"NeneJump11"},
    {url:"./nene/Jump (12).png",name:"NeneJump12"},
    {url:"./nene/Jump (13).png",name:"NeneJump13"},
    {url:"./nene/Jump (14).png",name:"NeneJump14"},
    {url:"./nene/Jump (15).png",name:"NeneJump15"},

    {url:"./nene/Run (1).png",name:"NeneRun1"},
    {url:"./nene/Run (2).png",name:"NeneRun2"},
    {url:"./nene/Run (3).png",name:"NeneRun3"},
    {url:"./nene/Run (4).png",name:"NeneRun4"},
    {url:"./nene/Run (5).png",name:"NeneRun5"},
    {url:"./nene/Run (6).png",name:"NeneRun6"},
    {url:"./nene/Run (7).png",name:"NeneRun7"},
    {url:"./nene/Run (8).png",name:"NeneRun8"},
    {url:"./nene/Run (9).png",name:"NeneRun9"},
    {url:"./nene/Run (10).png",name:"NeneRun10"},
    {url:"./nene/Run (11).png",name:"NeneRun11"},
    {url:"./nene/Run (12).png",name:"NeneRun12"},
    {url:"./nene/Run (13).png",name:"NeneRun13"},
    {url:"./nene/Run (14).png",name:"NeneRun14"},
    {url:"./nene/Run (15).png",name:"NeneRun15"},

    {url:"./nene/Dead (1).png",name:"NeneDead1"},
    {url:"./nene/Dead (2).png",name:"NeneDead2"},
    {url:"./nene/Dead (3).png",name:"NeneDead3"},
    {url:"./nene/Dead (4).png",name:"NeneDead4"},
    {url:"./nene/Dead (5).png",name:"NeneDead5"},
    {url:"./nene/Dead (6).png",name:"NeneDead6"},
    {url:"./nene/Dead (7).png",name:"NeneDead7"},
    {url:"./nene/Dead (8).png",name:"NeneDead8"},
    {url:"./nene/Dead (9).png",name:"NeneDead9"},
    {url:"./nene/Dead (10).png",name:"NeneDead10"},
    {url:"./nene/Dead (11).png",name:"NeneDead11"},
    {url:"./nene/Dead (12).png",name:"NeneDead12"},
    {url:"./nene/Dead (13).png",name:"NeneDead13"},
    {url:"./nene/Dead (14).png",name:"NeneDead14"},
    {url:"./nene/Dead (15).png",name:"NeneDead15"},

    {url:"./nena/Idle (1).png",name:"NenaIdle1"},
    {url:"./nena/Idle (2).png",name:"NenaIdle2"},
    {url:"./nena/Idle (3).png",name:"NenaIdle3"},
    {url:"./nena/Idle (4).png",name:"NenaIdle4"},
    {url:"./nena/Idle (5).png",name:"NenaIdle5"},
    {url:"./nena/Idle (6).png",name:"NenaIdle6"},
    {url:"./nena/Idle (7).png",name:"NenaIdle7"},
    {url:"./nena/Idle (8).png",name:"NenaIdle8"},
    {url:"./nena/Idle (9).png",name:"NenaIdle9"},
    {url:"./nena/Idle (10).png",name:"NenaIdle10"},
    {url:"./nena/Idle (11).png",name:"NenaIdle11"},
    {url:"./nena/Idle (12).png",name:"NenaIdle12"},
    {url:"./nena/Idle (13).png",name:"NenaIdle13"},
    {url:"./nena/Idle (14).png",name:"NenaIdle14"},
    {url:"./nena/Idle (15).png",name:"NenaIdle15"},
    {url:"./nena/Idle (16).png",name:"NenaIdle16"},

    {url:"./nena/Walk (1).png",name:"NenaWalk1"},
    {url:"./nena/Walk (2).png",name:"NenaWalk2"},
    {url:"./nena/Walk (3).png",name:"NenaWalk3"},
    {url:"./nena/Walk (4).png",name:"NenaWalk4"},
    {url:"./nena/Walk (5).png",name:"NenaWalk5"},
    {url:"./nena/Walk (6).png",name:"NenaWalk6"},
    {url:"./nena/Walk (7).png",name:"NenaWalk7"},
    {url:"./nena/Walk (8).png",name:"NenaWalk8"},
    {url:"./nena/Walk (9).png",name:"NenaWalk9"},
    {url:"./nena/Walk (10).png",name:"NenaWalk10"},
    {url:"./nena/Walk (11).png",name:"NenaWalk11"},
    {url:"./nena/Walk (12).png",name:"NenaWalk12"},
    {url:"./nena/Walk (13).png",name:"NenaWalk13"},
    {url:"./nena/Walk (14).png",name:"NenaWalk14"},
    {url:"./nena/Walk (15).png",name:"NenaWalk15"},
    {url:"./nena/Walk (16).png",name:"NenaWalk16"},
    {url:"./nena/Walk (17).png",name:"NenaWalk17"},
    {url:"./nena/Walk (18).png",name:"NenaWalk18"},
    {url:"./nena/Walk (19).png",name:"NenaWalk19"},
    {url:"./nena/Walk (20).png",name:"NenaWalk20"},

    {url:"./nena/Jump (1).png",name:"NenaJump1"},
    {url:"./nena/Jump (2).png",name:"NenaJump2"},
    {url:"./nena/Jump (3).png",name:"NenaJump3"},
    {url:"./nena/Jump (4).png",name:"NenaJump4"},
    {url:"./nena/Jump (5).png",name:"NenaJump5"},
    {url:"./nena/Jump (6).png",name:"NenaJump6"},
    {url:"./nena/Jump (7).png",name:"NenaJump7"},
    {url:"./nena/Jump (8).png",name:"NenaJump8"},
    {url:"./nena/Jump (9).png",name:"NenaJump9"},
    {url:"./nena/Jump (10).png",name:"NenaJump10"},
    {url:"./nena/Jump (11).png",name:"NenaJump11"},
    {url:"./nena/Jump (12).png",name:"NenaJump12"},
    {url:"./nena/Jump (13).png",name:"NenaJump13"},
    {url:"./nena/Jump (14).png",name:"NenaJump14"},
    {url:"./nena/Jump (15).png",name:"NenaJump15"},

    {url:"./nena/Run (1).png",name:"NenaRun1"},
    {url:"./nena/Run (2).png",name:"NenaRun2"},
    {url:"./nena/Run (3).png",name:"NenaRun3"},
    {url:"./nena/Run (4).png",name:"NenaRun4"},
    {url:"./nena/Run (5).png",name:"NenaRun5"},
    {url:"./nena/Run (6).png",name:"NenaRun6"},
    {url:"./nena/Run (7).png",name:"NenaRun7"},
    {url:"./nena/Run (8).png",name:"NenaRun8"},
    {url:"./nena/Run (9).png",name:"NenaRun9"},
    {url:"./nena/Run (10).png",name:"NenaRun10"},
    {url:"./nena/Run (11).png",name:"NenaRun11"},
    {url:"./nena/Run (12).png",name:"NenaRun12"},
    {url:"./nena/Run (13).png",name:"NenaRun13"},
    {url:"./nena/Run (14).png",name:"NenaRun14"},
    {url:"./nena/Run (15).png",name:"NenaRun15"},
    {url:"./nena/Run (16).png",name:"NenaRun16"},
    {url:"./nena/Run (17).png",name:"NenaRun17"},
    {url:"./nena/Run (18).png",name:"NenaRun18"},
    {url:"./nena/Run (19).png",name:"NenaRun19"},
    {url:"./nena/Run (20).png",name:"NenaRun20"},

    {url:"./nena/Dead (1).png",name:"NenaDead1"},
    {url:"./nena/Dead (2).png",name:"NenaDead2"},
    {url:"./nena/Dead (3).png",name:"NenaDead3"},
    {url:"./nena/Dead (4).png",name:"NenaDead4"},
    {url:"./nena/Dead (5).png",name:"NenaDead5"},
    {url:"./nena/Dead (6).png",name:"NenaDead6"},
    {url:"./nena/Dead (7).png",name:"NenaDead7"},
    {url:"./nena/Dead (8).png",name:"NenaDead8"},
    {url:"./nena/Dead (9).png",name:"NenaDead9"},
    {url:"./nena/Dead (10).png",name:"NenaDead10"},
    {url:"./nena/Dead (11).png",name:"NenaDead11"},
    {url:"./nena/Dead (12).png",name:"NenaDead12"},
    {url:"./nena/Dead (13).png",name:"NenaDead13"},
    {url:"./nena/Dead (14).png",name:"NenaDead14"},
    {url:"./nena/Dead (15).png",name:"NenaDead15"},

    {url:"./Enemies/mosquitos/tile000.png",name:"Mosquito1"},
    {url:"./Enemies/mosquitos/tile001.png",name:"Mosquito2"},
    {url:"./Enemies/mosquitos/tile002.png",name:"Mosquito3"},
    {url:"./Enemies/mosquitos/tile003.png",name:"Mosquito4"},
    {url:"./Enemies/mosquitos/tile004.png",name:"Mosquito5"},
    {url:"./Enemies/mosquitos/tile005.png",name:"Mosquito6"},
    {url:"./Enemies/mosquitos/tile006.png",name:"Mosquito7"},
    {url:"./Enemies/mosquitos/tile007.png",name:"Mosquito8"},
    {url:"./Enemies/mosquitos/tile008.png",name:"Mosquito9"},
    {url:"./Enemies/mosquitos/tile009.png",name:"Mosquito10"},
    {url:"./Enemies/mosquitos/tile010.png",name:"Mosquito11"},
    {url:"./Enemies/mosquitos/tile011.png",name:"Mosquito12"},
    
    {url:"./Enemies/snake/tile024.png",name:"Snake1"},
    {url:"./Enemies/snake/tile025.png",name:"Snake2"},
    {url:"./Enemies/snake/tile026.png",name:"Snake3"},
    {url:"./Enemies/snake/tile027.png",name:"Snake4"},
    {url:"./Enemies/snake/tile028.png",name:"Snake5"},
    {url:"./Enemies/snake/tile029.png",name:"Snake6"},
    {url:"./Enemies/snake/tile030.png",name:"Snake7"},
    {url:"./Enemies/snake/tile031.png",name:"Snake8"},
    {url:"./Enemies/snake/tile008.png",name:"Snake9"},
    {url:"./Enemies/snake/tile009.png",name:"Snake10"},
    {url:"./Enemies/snake/tile010.png",name:"Snake11"},
    {url:"./Enemies/snake/tile011.png",name:"Snake12"},

    {url:"./Tiles/Tile (1).png",name:"Tile1"},
    {url:"./Tiles/Tile (2).png",name:"Tile2"},
    {url:"./Tiles/Tile (3).png",name:"Tile3"},
    {url:"./Tiles/Tile (4).png",name:"Tile4"},
    {url:"./Tiles/Tile (5).png",name:"Tile5"},
    {url:"./Tiles/Tile (6).png",name:"Tile6"},
    {url:"./Tiles/Tile (7).png",name:"Tile7"},
    {url:"./Tiles/Tile (8).png",name:"Tile8"},
    {url:"./Tiles/Tile (9).png",name:"Tile9"},
    {url:"./Tiles/Tile (10).png",name:"Tile10"},
    {url:"./Tiles/Tile (11).png",name:"Tile11"},
    {url:"./Tiles/Tile (14).png",name:"Tile14"},
    {url:"./Tiles/Tile (15).png",name:"Tile15"},
    {url:"./Tiles/Tile (16).png",name:"Tile16"},

    {url:"./Tiles/Agua.png",name:"Agua"},
    {url:"./Tiles/Agua1.png",name:"Agua1"},

    {url:"./HUD/hud_0.png",name:"0"},
    {url:"./HUD/hud_heartEmpty.png",name:"HeartEmpty"},
    {url:"./HUD/hud_heartFullx0.png",name:"HeartFullx0"},
    {url:"./HUD/hud_heartFullx0.5.png",name:"HeartFullx0.5"},
    {url:"./HUD/hud_heartFullx1.png",name:"HeartFullx1"},
    {url:"./HUD/hud_heartFullx1.5.png",name:"HeartFullx1.5"},
    {url:"./HUD/hud_heartFullx2.png",name:"HeartFullx2"},
    {url:"./HUD/hud_heartFullx2.5.png",name:"HeartFullx2.5"},
    {url:"./HUD/hud_heartFullx3.png",name:"HeartFull"},
    {url:"./HUD/hud_heartHalf.png",name:"HeartHalf"},
    {url:"./HUD/tan_pressed.png",name:"BotonMenuPressed"},
    {url:"./HUD/tan.png",name:"BotonMenu"},
    {url:"./HUD/timmy.png",name:"Timmy"},
    {url:"./HUD/becky.png",name:"Becky"},
    {url:"./HUD/fondoPlayer.png",name:"FondoPlayer"},
    {url:"./HUD/fondoPlayer1.png",name:"FondoPlayer1"},
    {url:"./HUD/fondoPlayer2.png",name:"FondoPlayer2"},

    {url:"./UI/configBt.png",name:"buttonConfig"},
    {url:"./UI/configBt_pressed.png",name:"buttonConfigPress"},
    {url:"./UI/beckyBt.png",name:"buttonbecky"},
    {url:"./UI/beckyBt_pressed.png",name:"buttonbeckyPress"},
    {url:"./UI/comenzarBt.png",name:"buttoncomenzar"},
    {url:"./UI/comenzarBt_pressed.png",name:"buttoncomenzarPress"},
    {url:"./UI/salirBt.png",name:"buttonExit"},
    {url:"./UI/salirBt_pressed.png",name:"buttonExitPress"},
    {url:"./UI/timmyBt.png",name:"buttontimmy"},
    {url:"./UI/timmyBt_pressed.png",name:"buttontimmyPress"},
    {url:"./UI/eligePlayer.png",name:"TituloElige"},
    {url:"./UI/tituloGame.png",name:"TituloGame"},
    {url:"./UI/fondoPP.jpg",name:"FondoUI"},


    {url:"./Object/Bush (4).png",name:"Arbusto"},
    {url:"./Object/Bush (1).png",name:"Arbusto1"},
    {url:"./Object/Stone.png",name:"Stone"},
    {url:"./Object/Sign_1.png",name:"Señal1"},
    {url:"./Object/Sign_2.png",name:"Señal2"},
    {url:"./Object/Tree_1.png",name:"Tronco"},
    {url:"./Object/Tree_2.png",name:"Arbol1"},
    {url:"./Object/Tree_3.png",name:"Arbol2"},
    {url:"./Object/flagGreen.png",name:"BanderaVerde1"},
    {url:"./Object/flagGreen2.png",name:"BanderaVerde2"},
    {url:"./Object/flagGreenHanging.png",name:"BanderaVerdeCaida"},

    

]